import React, { useState } from 'react';
import { ArrowLeft, Check, MapPin, Package, ShieldCheck, Truck } from 'lucide-react';
import { useKairos } from '../context/KairosContext';
import mamaImg from '../assets/images/poultry_farm_1787307776327.jpg';

const priorities = ['Map reliable rural crop and spice suppliers', 'Set quality, grading, and storage standards', 'Build wholesale relationships in Dar es Salaam', 'Validate export requirements before scaling'];

export const MamaKubwaView: React.FC = () => {
  const { setActiveTab } = useKairos();
  const [completed, setCompleted] = useState<string[]>([]);
  const togglePriority = (priority: string) => setCompleted((current) => current.includes(priority) ? current.filter((item) => item !== priority) : [...current, priority]);
  return <div className="space-y-8 pb-12 text-black dark:text-white">
    <div className="flex items-center justify-between"><button type="button" onClick={() => setActiveTab('dashboard')} className="inline-flex items-center gap-2 text-xs font-semibold text-black hover:text-emerald-700 dark:text-white dark:hover:text-emerald-300"><ArrowLeft className="h-4 w-4" /> Back to Overview</button><span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-950 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200"><ShieldCheck className="h-3.5 w-3.5" /> Founder approved</span></div>
    <section className="overflow-hidden rounded-3xl border border-stone-200 bg-white shadow-sm dark:border-stone-800 dark:bg-stone-900"><div className="grid lg:grid-cols-12"><div className="flex flex-col justify-between p-6 sm:p-8 lg:col-span-8"><div><p className="text-xs font-semibold uppercase tracking-[0.18em]">Chapter 03 · Rural supply and trade</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Mama Kubwa Enterprises</h1><p className="mt-3 max-w-2xl text-sm leading-relaxed">A crop and spice storage and supply business moving quality produce from rural areas to Dar es Salaam wholesalers, with a path toward export.</p></div><div className="mt-8 flex flex-wrap gap-x-8 gap-y-3 border-t border-stone-200 pt-4 text-xs font-semibold dark:border-stone-700"><span>Operations: Mom and Dad</span><span>Approval and founding: You</span></div></div><div className="min-h-56 lg:col-span-4"><img src={mamaImg} alt="Rural agricultural production" className="h-full w-full object-cover" /></div></div></section>
    <section className="grid gap-4 sm:grid-cols-3" aria-label="Mama Kubwa summary dashboard">{[['Sourcing', 'Rural producer network', MapPin], ['Operations', 'Storage and quality', Package], ['Sales', 'Wholesale and export', Truck]].map(([label, value, Icon]) => <div key={label as string} className="rounded-2xl border border-stone-200 bg-white p-5 dark:border-stone-800 dark:bg-stone-900"><Icon className="h-5 w-5 text-emerald-800 dark:text-emerald-300" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.14em]">{label as string}</p><p className="mt-1 text-sm font-semibold">{value as string}</p></div>)}</section>
    <div className="grid gap-6 lg:grid-cols-5"><section className="rounded-2xl border border-stone-200 bg-[#FDFBF7] p-6 dark:border-stone-800 dark:bg-stone-900 lg:col-span-3"><p className="text-xs font-semibold uppercase tracking-[0.16em]">Operating principle</p><h2 className="mt-2 text-xl font-semibold">Build trust in the supply chain before chasing scale.</h2><p className="mt-3 text-sm leading-relaxed">Use the same planning discipline as the Zanzibar venture: define setup needs, recurring costs, quality controls, demand, and the route to reliable monthly cash flow.</p><div className="mt-6 grid gap-3 text-sm"><div className="flex justify-between border-b border-stone-200 pb-3 dark:border-stone-700"><span>Core products</span><strong>Crops and spices</strong></div><div className="flex justify-between"><span>Route to market</span><strong>Rural → Dar → export</strong></div></div></section><section className="rounded-2xl border border-stone-200 bg-white p-6 dark:border-stone-800 dark:bg-stone-900 lg:col-span-2"><p className="text-xs font-semibold uppercase tracking-[0.16em]">Monthly summary</p><div className="mt-5 grid gap-4"><div><p className="text-xs">Current stage</p><p className="mt-1 text-lg font-semibold">Supply chain validation</p></div><div><p className="text-xs">Priority this month</p><p className="mt-1 text-sm font-semibold">Confirm suppliers and storage</p></div><div><p className="text-xs">Founder note</p><p className="mt-1 text-sm leading-relaxed">Consistency, records, and quality will make the business export-ready.</p></div></div></section></div>
    <section className="rounded-2xl border border-stone-200 bg-white p-6 dark:border-stone-800 dark:bg-stone-900"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em]">Next decisions</p><h2 className="mt-2 text-xl font-semibold">Build the supply chain before chasing scale.</h2></div><span className="text-xs font-semibold">{completed.length}/{priorities.length} done</span></div><div className="mt-5 grid gap-2">{priorities.map((priority) => { const isDone = completed.includes(priority); return <button key={priority} type="button" onClick={() => togglePriority(priority)} className="flex items-center gap-3 rounded-lg border border-stone-200 px-3 py-3 text-left text-sm transition-colors hover:bg-stone-50 dark:border-stone-700 dark:hover:bg-stone-800"><span className={`flex size-5 shrink-0 items-center justify-center rounded-full border ${isDone ? 'border-emerald-700 bg-emerald-700 text-white' : 'border-stone-500 text-transparent'}`}><Check className="h-3 w-3" /></span><span className={isDone ? 'text-stone-500 line-through' : ''}>{priority}</span></button>; })}</div></section>
  </div>;
};
export default MamaKubwaView;
