import React, { useState } from 'react';
import { Check, Package, Palette, ShoppingBag, Truck } from 'lucide-react';

const priorities = ['Define the first capsule collection', 'Confirm reliable blank garment suppliers', 'Create a simple product and pricing sheet', 'Test sales through friends, pop-ups, and online orders'];

export const SteazyView: React.FC = () => {
  const [completed, setCompleted] = useState<string[]>([]);
  const toggle = (item: string) => setCompleted((current) => current.includes(item) ? current.filter((entry) => entry !== item) : [...current, item]);
  return <div className="space-y-6 pb-12">
    <header className="border-b border-stone-200 pb-6 dark:border-stone-800"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-stone-500">New venture</p><div className="mt-2 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-semibold tracking-tight text-stone-950 dark:text-stone-100">Steazy</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-stone-600 dark:text-stone-400">A clothing and accessories brand for thoughtful everyday pieces: T-shirts, caps, tote bags, and whatever the next collection calls for.</p></div><span className="inline-flex w-fit rounded-full border border-violet-200 bg-violet-50 px-3 py-1.5 text-xs font-semibold text-violet-900 dark:border-violet-900 dark:bg-violet-950/40 dark:text-violet-300">Founder idea</span></div></header>
    <section className="grid gap-4 sm:grid-cols-3" aria-label="Steazy focus areas"><div className="rounded-xl border border-stone-200 bg-white p-5 dark:border-stone-800 dark:bg-stone-900"><Palette className="size-5 text-violet-700 dark:text-violet-400" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.14em] text-stone-500">Identity</p><p className="mt-1 text-sm font-medium text-stone-900 dark:text-stone-100">A clear visual language</p><p className="mt-2 text-xs leading-relaxed text-stone-500">Build a recognizable point of view before making too many products.</p></div><div className="rounded-xl border border-stone-200 bg-white p-5 dark:border-stone-800 dark:bg-stone-900"><ShoppingBag className="size-5 text-violet-700 dark:text-violet-400" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.14em] text-stone-500">Products</p><p className="mt-1 text-sm font-medium text-stone-900 dark:text-stone-100">Small, useful collections</p><p className="mt-2 text-xs leading-relaxed text-stone-500">T-shirts, caps, totes, and accessories made in focused drops.</p></div><div className="rounded-xl border border-stone-200 bg-white p-5 dark:border-stone-800 dark:bg-stone-900"><Truck className="size-5 text-violet-700 dark:text-violet-400" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.14em] text-stone-500">Market</p><p className="mt-1 text-sm font-medium text-stone-900 dark:text-stone-100">Direct and wholesale</p><p className="mt-2 text-xs leading-relaxed text-stone-500">Start close to home, learn what sells, then grow into wholesale relationships.</p></div></section>
    <section className="rounded-xl border border-stone-200 bg-white p-5 dark:border-stone-800 dark:bg-stone-900" aria-labelledby="steazy-priorities"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-stone-500">First moves</p><h2 id="steazy-priorities" className="mt-2 text-lg font-semibold text-stone-950 dark:text-stone-100">Make the first drop small and memorable.</h2></div><span className="text-xs text-stone-500">{completed.length}/{priorities.length} done</span></div><div className="mt-4 grid gap-2">{priorities.map((item) => { const done = completed.includes(item); return <button key={item} type="button" onClick={() => toggle(item)} className="flex items-center gap-3 rounded-lg border border-stone-200 px-3 py-3 text-left text-sm transition-colors hover:bg-stone-50 dark:border-stone-800 dark:hover:bg-stone-800/60"><span className={`flex size-5 shrink-0 items-center justify-center rounded-full border ${done ? 'border-violet-700 bg-violet-700 text-white' : 'border-stone-300 text-transparent dark:border-stone-600'}`}><Check className="size-3" /></span><span className={done ? 'text-stone-400 line-through' : 'text-stone-700 dark:text-stone-300'}>{item}</span></button>; })}</div></section>
    <div className="flex items-center gap-2 text-xs text-stone-500"><Package className="size-4" /> Keep this as an idea until the first product, supplier, and customer are clear.</div>
  </div>;
};
export default SteazyView;
